name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  REGISTRY: ghcr.io

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@protoc
      - uses: dtolnay/rust-toolchain@beta
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Check
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings
      - name: rustfmt
        run: cargo fmt --all --check
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@protoc
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test
  publish:
    #    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        id: extractBranchName
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN }}

      - name: Build image name
        shell: bash
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          if [ $BRANCH_NAME = 'master']; then
            echo 'IMAGE_NAME=ghcr.io/inozpavel/kafka-reader:master' >> $GITHUB_OUTPUT
          else
            echo 'IMAGE_NAME=ghcr.io/inozpavel/kafka-reader:dev' >> $GITHUB_OUTPUT
          fi
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ steps.extractBranchName.outputs.IMAGE_NAME }}
            "ghcr.io/inozpavel/kafka-reader:latest"
